version: '3'

volumes:
  metrics_local_postgres_data: {}
  metrics_local_postgres_data_backups: {}
  production_postgres_data_pg: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: metrics_local_django
    container_name: metrics_local_django
    depends_on:
      - postgres
      - pgbouncer
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: metrics_production_postgres
    container_name: metrics_local_postgres
    volumes:
      - metrics_local_postgres_data:/home/postgres/pgdata/data
      - metrics_local_postgres_data_backups:/backups
      - production_postgres_data_pg:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  pgbouncer:
    image: edoburu/pgbouncer
    env_file:
       - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    depends_on:
      - postgres

  docs:
    image: metrics_local_docs
    container_name: metrics_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./metrics:/app/metrics:z
    ports:
      - '9000:9000'
    command: /start-docs
