# Generated by Django 4.2.2 on 2023-06-29 19:27

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirQuality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.models.generate_ulid, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("pm2_5_value", models.FloatField()),
                ("pm10_value", models.FloatField()),
                ("source_id", models.UUIDField()),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
