# Generated by Django 4.2.2 on 2023-12-02 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirQuality",
            fields=[
                ("pm2_5_value", models.FloatField()),
                ("pm10_value", models.FloatField()),
                ("source_id", models.UUIDField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
