# Generated by Django 4.2.2 on 2023-10-24 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("aqi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airquality",
            name="id",
        ),
        migrations.RemoveField(
            model_name="airquality",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="airquality",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
            SELECT create_hypertable('aqi_airquality', 'created_at');
            """,
            reverse_sql="""
            -- Add reverse SQL here if necessary
            """,
        ),
    ]
