# Generated by Django 4.2.2 on 2023-10-31 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aqi", "0002_remove_airquality_id_remove_airquality_updated_at_and_more"),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW pm_metrics_summary_hourly
            WITH (timescaledb.continuous) AS
            SELECT source_id,
            time_bucket(INTERVAL '1 hour', aqi_airquality.created_at) AS bucket,
            AVG(pm2_5_value) as pm2_5_value_avg,
            MAX(pm2_5_value) as pm2_5_value_max,
            MIN(pm2_5_value) as pm2_5_value_min,
            AVG(pm10_value) as pm10_value_avg,
            MAX(pm10_value) as pm10_value_max,
            MIN(pm10_value) as pm10_value_min
            FROM aqi_airquality
            GROUP BY source_id, bucket WITH NO data;

            SELECT add_continuous_aggregate_policy('pm_metrics_summary_hourly',
            start_offset => INTERVAL '1 hour',
            end_offset => null,
            schedule_interval => INTERVAL '1 hour');
            """,
            reverse_sql="""
            Select remove_continuous_aggregate_policy(
            'pm_metrics_summary_hourly',
            false
            );
            DROP MATERIALIZED VIEW pm_metrics_summary_hourly;
            """,
        ),
    ]
