apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: application
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80  # Exposed port on the Service
    targetPort: 5000  # Port on the Pods
  type: LoadBalancer
