apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer
  namespace: application
type: Opaque
data:
  eyJpdiI6ImpRd1VPT1hVb1gzR1RsU2h1YzZSaWc9PSIsCiJ2IjoxLAoiaXRlciI6MTAwMCwKImtzIjoyNTYsCiJ0cyI6NjQsCiJtb2RlIjoiY2NtIiwKImFkYXRhIjoiIiwKImNpcGhlciI6ImFlcyIsCiJzYWx0Ijoickx1TmszS1g3cGc9IiwKImN0IjoiNHR0TmlmSmVIR1JpZ3VXMVBWRGlmbDd2T3RkYTBrSkdzR0Fhc0YrNXVuUlZicDQxVm5CQnFKemhVa1VPTWIxTUdjckpRcnQwWlM2dnhXbW5vbTMvaUVXeVFUWkZTNUkrTlBaUUdxdHNaUnhlM3RtNk51YWc2NGJacURCUXJ4L1VDa0NwUURRN3ZOMk1MdzI2TW5NNWo0OE1HRHBqb1gyZEdUTnR5S2tUVU1pak5nR2xpVEFBSkp2SGdMWEV1WHRuelVrUEVLTWllZ0hKZGFvV21YemdLZW92Q241RHJHalJPZFpjVk1SVC9MN1kxY2gwVHNkaXV2ZzNpTGpMaDNaMkhwT0FJamdoQ1dvMU0wU1Nhdk9QaE1VLzBSZk1mWHUxZ3NCZVl3U2o4citFSGpZZXNxL1pYZys5aWREektETjNwV1dIbEJQeXFZcXQwQnVJMkNRWFEyUVJjMHROMG9OQTY4c0hwMU55OGswMkpaYjBhQVVGaDNlZUgwd3I0OFZza0JaZDQwNlEzc2h6QVpZN1VYMWVmZTBXcUhVbG52Y0lYN2Nla1ZYclBNT0hNeElPMWZYdW9iZEhGQ3RNRFRGdDlkWElVQnNJeEprPSJ9

