apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: application
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 6432
      targetPort: 6432
  type: ClusterIP
