log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'

  web-secure:
    # https
    address: ':443'

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: 'contact@sreeraj.dev'
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router-api:
      rule: 'Host(`metrics.sreeraj.dev`) && (PathPrefix(`/api/`) || PathPrefix(`/admin/`))'
      entryPoints:
        - web-secure
        - web
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt
    web-non-secure-router-api:
      rule: 'Host(`metrics.sreeraj.dev`) && (PathPrefix(`/api/airquality`))'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django
    web-secure-router:
      rule: 'Host(`metrics.sreeraj.dev`)'
      entryPoints:
        - web-secure
      service: frontend
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
